### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by ChALkeR** [ncase/ncase.github.io#2]
Should be easy to do.

Refs:
* https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ 
* https://help.github.com/articles/troubleshooting-custom-domains/#https-errors
* https://help.github.com/articles/securing-your-github-pages-site-with-https/
* https://help.github.com/articles/using-a-custom-domain-with-github-pages/

Basically, all you need to do is update the A records to the ones mentioned in the second link (the same as the ones for `ncase.github.io`) or just use a CNAME record, and enable «Enforce HTTPS» in repo settings (if such a setting is present), and remove and re-add the domain to GitHub account.

Atm, accessing https://ncase.me results in `ERR_CERT_COMMON_NAME_INVALID` error.
And that's what some people try to use, e.g. with EFF HTTPS Everywhere addon enabled.

**Comment by ncase** [comment]
Oh that's amazing!  I was disappointed when I first found out Github Custom Domains couldn't do HTTPS, so this is especially happy news for me :) I'll implement it in the next couple weeks! (trying to take a work-break for a bit after just launching a big project)

**Comment by ncase** [comment]
![](https://i.ytimg.com/vi/m4onTqN7Ctk/maxresdefault.jpg)

Alright I finally did it!  https://ncase.me/ same for all the projects on the site, too.  Thanks again for alerting me to Github Pages finally allowing https on custom domains!
