### ISSUE TITLE
Broken link to "Kurt Vonnegut’s 8 Tenets of Storytelling"

### ISSUE THREAD

**Issue by scsmash3r** [ncase/ncase.github.io#7]
https://github.com/ncase/ncase.github.io/blob/da7c58e7eae504b6035dcde6c28516381d40a15b/faq/index.html#L251

`%03` breaks whole link while on live website.

<details>
  <summary></summary>
  P.S. Your website and materials are awesome, helped me to improve lots of stuff! Thank you!
</details>

**Comment by ncase** [comment]
Whoops, dunno how that snuck in there. Fixed! https://github.com/ncase/ncase.github.io/commit/57111282d887c07f34634781d31cde6c1884f2e7  (Apologies for, uh, 4-month-delayed fix.)
